#!/usr/bin/env python3
# Création composants SmartOrder Next.js v3.0

import os

BASE_DIR = "/opt/smartorder-pro/dashboard-nextjs/src/components/smartorder"
os.chdir(BASE_DIR)

# Liste des composants à créer (code minifié sans espaces inutiles)
components = {
    "ModeSelector.tsx": '"use client";import {useState} from "react";import {API_CONFIG} from "@/lib/smartorder-api";export default function ModeSelector(){const [mode,setMode]=useState("futures");const handleMode=async(m:string)=>{setMode(m);try{await fetch(API_CONFIG.BASE_URL+"/mode",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:m})});}catch(e){}};return <div className="glassmorphism p-4 rounded-lg flex gap-2">{["spot","futures","hybrid"].map(m=><button key={m} onClick={()=>handleMode(m)} className={(mode===m?"bg-blue-500 text-white":"bg-gray-700 text-gray-300")+" px-4 py-2 rounded font-semibold"}>{m.toUpperCase()}</button>)}</div>;}',
    
    "RiskPanel.tsx": '"use client";import {useState,useEffect} from "react";import {Shield} from "lucide-react";import {API_CONFIG,safe,formatPercent} from "@/lib/smartorder-api";export default function RiskPanel(){const [risk,setRisk]=useState(null);const [loading,setLoading]=useState(true);useEffect(()=>{const f=async()=>{try{const r=await fetch(API_CONFIG.BASE_URL+API_CONFIG.ENDPOINTS.RISK_STATUS);const d=await r.json();setRisk(d);}catch(e){}finally{setLoading(false);}};f();const i=setInterval(f,3000);return()=>clearInterval(i);},[]);if(loading)return <div className="glassmorphism p-6 rounded-xl animate-pulse"><div className="h-8 bg-gray-700/50 rounded"/></div>;const reliability=safe(risk?.reliability_score,0);return <div className="glassmorphism p-6 rounded-xl"><h2 className="text-2xl font-bold mb-6 flex items-center gap-2"><Shield className="w-6 h-6 text-green-500"/>Risk Status</h2><div className="space-y-4"><div><span className="text-gray-400">Reliability:</span> <span className="text-white font-bold">{reliability}%</span></div><div><span className="text-gray-400">Mode:</span> <span className="text-white font-bold">{risk?.current_mode||"N/A"}</span></div></div></div>;}',
    
    "ExchangeSelector.tsx": '"use client";import {useState,useEffect} from "react";import {Activity} from "lucide-react";import {API_CONFIG,safe} from "@/lib/smartorder-api";export default function ExchangeSelector(){const [exchanges,setExchanges]=useState<any[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{const f=async()=>{try{const r=await fetch(API_CONFIG.BASE_URL+API_CONFIG.ENDPOINTS.EXCHANGES_STATUS);const d=await r.json();setExchanges(d.exchanges||[]);}catch(e){}finally{setLoading(false);}};f();const i=setInterval(f,5000);return()=>clearInterval(i);},[]);if(loading)return <div className="glassmorphism p-6 rounded-xl animate-pulse"><div className="h-8 bg-gray-700/50 rounded"/></div>;return <div className="glassmorphism p-6 rounded-xl"><h2 className="text-2xl font-bold mb-6 flex items-center gap-2"><Activity className="w-6 h-6 text-blue-500"/>Exchanges</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{exchanges.map(ex=>(<div key={ex.exchange_id} className="glassmorphism p-4 rounded-lg"><h3 className="font-bold text-white">{ex.name}</h3><div className="text-xs text-gray-400">Latency: {safe(ex.latency_ms,0)}ms</div></div>))}</div></div>;}',
    
    "AIDecisionsBadge.tsx": '"use client";import {TrendingUp,TrendingDown,Minus} from "lucide-react";export default function AIDecisionsBadge({action,confidence,reasoning,size}:any){if(!action)return null;const colors={BUY:"bg-green-500/20 text-green-400",SELL:"bg-red-500/20 text-red-400",HOLD:"bg-yellow-500/20 text-yellow-400"};const Icon=action==="BUY"?TrendingUp:action==="SELL"?TrendingDown:Minus;return <div className={"inline-flex items-center gap-1 rounded px-2 py-1 text-xs "+colors[action]} title={reasoning}><Icon className="w-3 h-3"/><span>{action}</span>{confidence&&<span className="opacity-75">{Math.round(confidence)}%</span>}</div>;}',
    
    "StrategiesPanel.tsx": '"use client";import {useState,useEffect} from "react";import {Brain} from "lucide-react";import {API_CONFIG,safe,formatPercent} from "@/lib/smartorder-api";export default function StrategiesPanel(){const [strategies,setStrategies]=useState<any[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{const f=async()=>{try{const r=await fetch(API_CONFIG.BASE_URL+API_CONFIG.ENDPOINTS.STRATEGIES);const d=await r.json();setStrategies(d.strategies||[]);}catch(e){}finally{setLoading(false);}};f();const i=setInterval(f,5000);return()=>clearInterval(i);},[]);if(loading)return <div className="glassmorphism p-6 rounded-xl animate-pulse"><div className="h-8 bg-gray-700/50 rounded"/></div>;return <div className="glassmorphism p-6 rounded-xl"><h2 className="text-2xl font-bold mb-6 flex items-center gap-2"><Brain className="w-6 h-6 text-purple-500"/>Strategies ({strategies.length})</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{strategies.map(s=>{const score=safe(s.score,0);const perf=safe(s.performance_24h,0);return <div key={s.strategy_id} className="glassmorphism p-4 rounded-lg"><h3 className="font-bold text-white mb-2">{s.name}</h3><div className="mb-2"><span className="text-gray-400 text-sm">Score:</span> <span className="text-white font-bold">{score}/100</span></div><div className="w-full bg-gray-700 rounded-full h-2"><div className="bg-purple-500 h-2 rounded-full" style={{width:score+"%"}}/></div><div className="mt-2 text-xs text-gray-400">24h: <span className={perf>=0?"text-green-400":"text-red-400"}>{formatPercent(perf)}</span></div></div>;})}</div></div>;}',
    
    "PositionsTable.tsx": '"use client";import {useState,useEffect} from "react";import {BarChart3} from "lucide-react";import {API_CONFIG,safe,formatCurrency} from "@/lib/smartorder-api";import AIDecisionsBadge from "./AIDecisionsBadge";export default function PositionsTable(){const [positions,setPositions]=useState<any[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{const f=async()=>{try{const r=await fetch(API_CONFIG.BASE_URL+API_CONFIG.ENDPOINTS.POSITIONS);const d=await r.json();setPositions(d.futures||[]);}catch(e){}finally{setLoading(false);}};f();const i=setInterval(f,3000);return()=>clearInterval(i);},[]);if(loading)return <div className="glassmorphism p-6 rounded-xl animate-pulse"><div className="h-64 bg-gray-700/50 rounded"/></div>;return <div className="glassmorphism p-6 rounded-xl"><h2 className="text-2xl font-bold mb-6 flex items-center gap-2"><BarChart3 className="w-6 h-6 text-blue-500"/>Positions ({positions.length})</h2>{positions.length===0?<div className="text-center py-12 text-gray-400">No open positions</div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-gray-400 text-sm border-b border-gray-700"><th className="pb-3 px-2">Symbol</th><th className="pb-3 px-2">Side</th><th className="pb-3 px-2">Size</th><th className="pb-3 px-2">Entry</th><th className="pb-3 px-2">Current</th><th className="pb-3 px-2">PnL</th><th className="pb-3 px-2">AI</th></tr></thead><tbody>{positions.map(p=>{const pnl=safe(p.unrealized_pnl,0);return <tr key={p.position_id} className="border-b border-gray-700/30"><td className="py-4 px-2 font-bold text-white">{p.symbol}</td><td className="py-4 px-2"><span className={"px-2 py-1 rounded text-xs "+(p.side==="LONG"?"bg-green-500/20 text-green-400":"bg-red-500/20 text-red-400")}>{p.side}</span></td><td className="py-4 px-2 text-white font-mono">{safe(p.size,0).toFixed(4)}</td><td className="py-4 px-2 text-gray-300">{formatCurrency(p.entry_price)}</td><td className="py-4 px-2 text-white">{formatCurrency(p.current_price)}</td><td className="py-4 px-2"><div className={"font-bold "+(pnl>=0?"text-green-400":"text-red-400")}>{pnl>=0?"+":""}{formatCurrency(pnl)}</div></td><td className="py-4 px-2">{p.ai_recommendation?<AIDecisionsBadge action={p.ai_recommendation.action} confidence={p.ai_recommendation.confidence} reasoning={p.ai_recommendation.reasoning} size="sm"/>:<span className="text-gray-500 text-xs">-</span>}</td></tr>;})}</tbody></table></div>}</div>;}',
    
    "WalletUnified.tsx": '"use client";import {useState,useEffect} from "react";import {Wallet,TrendingUp,DollarSign,PieChart} from "lucide-react";import {API_CONFIG,safe,formatCurrency} from "@/lib/smartorder-api";export default function WalletUnified(){const [wallet,setWallet]=useState(null);const [loading,setLoading]=useState(true);useEffect(()=>{const f=async()=>{try{const r=await fetch(API_CONFIG.BASE_URL+API_CONFIG.ENDPOINTS.WALLET_UNIFIED);const d=await r.json();setWallet(d);}catch(e){}finally{setLoading(false);}};f();const i=setInterval(f,3000);return()=>clearInterval(i);},[]);if(loading)return <div className="glassmorphism p-6 rounded-xl animate-pulse"><div className="h-8 bg-gray-700/50 rounded"/></div>;const totalEquity=safe(wallet?.total_equity,0);const available=safe(wallet?.available_balance,0);const marginUsed=safe(wallet?.margin_used,0);const pnlTotal=safe(wallet?.pnl_total,0);const pnlDay=safe(wallet?.pnl_day,0);return <div className="glassmorphism p-6 rounded-xl"><h2 className="text-2xl font-bold mb-6 flex items-center gap-2"><Wallet className="w-6 h-6 text-yellow-500"/>Wallet</h2><div className="grid grid-cols-2 gap-4"><div className="glassmorphism p-4 rounded-lg"><div className="flex items-center justify-between mb-2"><span className="text-gray-400 text-sm">Total Equity</span><PieChart className="w-4 h-4 text-blue-400"/></div><div className="text-2xl font-bold text-white">{formatCurrency(totalEquity)}</div></div><div className="glassmorphism p-4 rounded-lg"><div className="flex items-center justify-between mb-2"><span className="text-gray-400 text-sm">Available</span><DollarSign className="w-4 h-4 text-green-400"/></div><div className="text-2xl font-bold text-white">{formatCurrency(available)}</div></div><div className="glassmorphism p-4 rounded-lg"><div className="flex items-center justify-between mb-2"><span className="text-gray-400 text-sm">Margin Used</span><TrendingUp className="w-4 h-4 text-orange-400"/></div><div className="text-2xl font-bold text-white">{formatCurrency(marginUsed)}</div></div><div className="glassmorphism p-4 rounded-lg"><div className="flex items-center justify-between mb-2"><span className="text-gray-400 text-sm">PnL Total</span><TrendingUp className={"w-4 h-4 "+(pnlTotal>=0?"text-green-400":"text-red-400")}/></div><div className={"text-2xl font-bold "+(pnlTotal>=0?"text-green-500":"text-red-500")}>{pnlTotal>=0?"+":""}{formatCurrency(pnlTotal)}</div><div className={"text-xs mt-1 "+(pnlDay>=0?"text-green-400":"text-red-400")}>Today: {pnlDay>=0?"+":""}{formatCurrency(pnlDay)}</div></div></div></div>;}',
}

for filename, code in components.items():
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(code)
    print(f'✅ {filename}')

print(f'\n✅ TOUS LES COMPOSANTS CRÉÉS ({len(components)} fichiers)')
